version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y git make gperf texinfo lzop xsltproc libxml-parser-perl
      - run: PROJECT=RPi ARCH=arm make image
